using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GopherTrip.API;
//
//    var stops = Stops.FromJson(jsonString);

namespace GopherTrip.API
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Stops
    {
        [JsonProperty("stop")]
        public List<Stop> Stop { get; set; }

        [JsonProperty("success")]
        public bool Success { get; set; }
    }

    public partial class Stop
    {
        [JsonProperty("ETA1")]
        public long Eta1 { get; set; }

        [JsonProperty("ETA2")]
        public long Eta2 { get; set; }

        [JsonProperty("routeID")]
        public long RouteId { get; set; }

        [JsonProperty("stopID")]
        public long StopId { get; set; }
    }

    public partial class Stops
    {
        public static Stops FromJson(string json) => JsonConvert.DeserializeObject<Stops>(json, GopherTrip.API.Converter.Settings);
    }
}
